In [1]:
# This is the first notebook to test the basics of the DataSet class
!wget https://sds-platform-private.s3-us-east-2.amazonaws.com/uploads/P87-Section-2-Dataset-Basics-Resources.zip

# import the necessary packages
import zipfile
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# unzip the file and close it
zipped_file = zipfile.ZipFile('P87-Section-2-Dataset-Basics-Resources.zip')
zipped_file.extractall()
zipped_file.close()

# Delete zip file
os.remove('P87-Section-2-Dataset-Basics-Resources.zip')

--2022-04-11 12:09:25--  https://sds-platform-private.s3-us-east-2.amazonaws.com/uploads/P87-Section-2-Dataset-Basics-Resources.zip
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving sds-platform-private.s3-us-east-2.amazonaws.com (sds-platform-private.s3-us-east-2.amazonaws.com)... 52.219.80.200
Connecting to sds-platform-private.s3-us-east-2.amazonaws.com (sds-platform-private.s3-us-east-2.amazonaws.com)|52.219.80.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54129 (53K) [application/x-zip-compressed]
Saving to: ‘P87-Section-2-Dataset-Basics-Resources.zip’

P87-Section-2-Datas 100%[===================>]  52.86K  --.-KB/s    in 0.05s

2022-04-11 12:09:25 (1.01 MB/s) - ‘P87-Section-2-Dataset-Basics-Resources.zip’ saved [54129/54129]

In [2]:
os.listdir()

['README.md',
 'Exploratory_Data_Analysis_Exercise.ipynb',
 '.git',
 'DataSetBasicsPractice.ipynb',
 'P87-S2-Dataset-Basics-Resources']

In [5]:
# change working directory to the folder containing the heart.csv file
os.chdir('P87-S2-Dataset-Basics-Resources')
# load the heart.csv file
heart_df = pd.read_csv('heart.csv')
# Change back to the original working directory
os.chdir('..')
# check the shape of the dataframe
heart_df.shape
# check the first 5 rows of the dataframe
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1